language: ruby
rvm:
  - 2.3.0
  - 2.5.3
  - 2.6.1
gemfile:
  - Gemfile
  - gemfiles/Gemfile-4-2
before_script: bundle install
script:
 - bundle exec rspec spec
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile-4-2
      rvm: 2.4.0
    - gemfile: Gemfile
      rvm: 2.1.8
